// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'2bd9d962850d2e58857853e5af9a0b0baa2e46111f058d70690c62b3f41aed9f'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Categoria: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly activo: CodecTypes['pg/bool@1']['output'];
    };
    readonly ListaReposicion: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly cantidadAReponer: CodecTypes['pg/numeric@1']['output'] | null;
      readonly fechaCreacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly productoId: CodecTypes['pg/int4@1']['output'];
      readonly proveedorId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Marca: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly activo: CodecTypes['pg/bool@1']['output'];
    };
    readonly MovimientoStock: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly tipo: 'ENTRADA' | 'SALIDA';
      readonly cantidad: CodecTypes['pg/numeric@1']['output'];
      readonly fecha: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly costoCompra: CodecTypes['pg/numeric@1']['output'] | null;
      readonly observacion: CodecTypes['pg/text@1']['output'] | null;
      readonly productoId: CodecTypes['pg/int4@1']['output'];
      readonly proveedorId: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly Producto: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly codigoBarra: CodecTypes['pg/text@1']['output'] | null;
      readonly presentacion: CodecTypes['pg/text@1']['output'] | null;
      readonly unidadStock: 'UNIDAD' | 'KILOGRAMO';
      readonly stockActual: CodecTypes['pg/numeric@1']['output'];
      readonly stockMinimo: CodecTypes['pg/numeric@1']['output'];
      readonly costoCompra: CodecTypes['pg/numeric@1']['output'];
      readonly precioSugerido: CodecTypes['pg/numeric@1']['output'] | null;
      readonly precioEfectivo: CodecTypes['pg/numeric@1']['output'];
      readonly precioTarjeta: CodecTypes['pg/numeric@1']['output'];
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly proveedorId: CodecTypes['pg/int4@1']['output'];
      readonly marcaId: CodecTypes['pg/int4@1']['output'];
    };
    readonly ProductoCategoria: {
      readonly productoId: CodecTypes['pg/int4@1']['output'];
      readonly categoriaId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Proveedor: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly telefono: CodecTypes['pg/text@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly activo: CodecTypes['pg/bool@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Categoria: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly activo: CodecTypes['pg/bool@1']['input'];
    };
    readonly ListaReposicion: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly cantidadAReponer: CodecTypes['pg/numeric@1']['input'] | null;
      readonly fechaCreacion: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly productoId: CodecTypes['pg/int4@1']['input'];
      readonly proveedorId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Marca: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly activo: CodecTypes['pg/bool@1']['input'];
    };
    readonly MovimientoStock: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly tipo: 'ENTRADA' | 'SALIDA';
      readonly cantidad: CodecTypes['pg/numeric@1']['input'];
      readonly fecha: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly costoCompra: CodecTypes['pg/numeric@1']['input'] | null;
      readonly observacion: CodecTypes['pg/text@1']['input'] | null;
      readonly productoId: CodecTypes['pg/int4@1']['input'];
      readonly proveedorId: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly Producto: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly codigoBarra: CodecTypes['pg/text@1']['input'] | null;
      readonly presentacion: CodecTypes['pg/text@1']['input'] | null;
      readonly unidadStock: 'UNIDAD' | 'KILOGRAMO';
      readonly stockActual: CodecTypes['pg/numeric@1']['input'];
      readonly stockMinimo: CodecTypes['pg/numeric@1']['input'];
      readonly costoCompra: CodecTypes['pg/numeric@1']['input'];
      readonly precioSugerido: CodecTypes['pg/numeric@1']['input'] | null;
      readonly precioEfectivo: CodecTypes['pg/numeric@1']['input'];
      readonly precioTarjeta: CodecTypes['pg/numeric@1']['input'];
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly proveedorId: CodecTypes['pg/int4@1']['input'];
      readonly marcaId: CodecTypes['pg/int4@1']['input'];
    };
    readonly ProductoCategoria: {
      readonly productoId: CodecTypes['pg/int4@1']['input'];
      readonly categoriaId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Proveedor: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly telefono: CodecTypes['pg/text@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly activo: CodecTypes['pg/bool@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly categoria: {
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
    };
    readonly listaReposicion: {
      readonly cantidadAReponer: CodecTypes['pg/numeric@1']['output'] | null;
      readonly fechaCreacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly productoId: CodecTypes['pg/int4@1']['output'];
      readonly proveedorId: CodecTypes['pg/int4@1']['output'];
    };
    readonly marca: {
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
    };
    readonly movimientoStock: {
      readonly cantidad: CodecTypes['pg/numeric@1']['output'];
      readonly costoCompra: CodecTypes['pg/numeric@1']['output'] | null;
      readonly fecha: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly observacion: CodecTypes['pg/text@1']['output'] | null;
      readonly productoId: CodecTypes['pg/int4@1']['output'];
      readonly proveedorId: CodecTypes['pg/int4@1']['output'] | null;
      readonly tipo: 'ENTRADA' | 'SALIDA';
    };
    readonly producto: {
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly codigoBarra: CodecTypes['pg/text@1']['output'] | null;
      readonly costoCompra: CodecTypes['pg/numeric@1']['output'];
      readonly descripcion: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly marcaId: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly precioEfectivo: CodecTypes['pg/numeric@1']['output'];
      readonly precioSugerido: CodecTypes['pg/numeric@1']['output'] | null;
      readonly precioTarjeta: CodecTypes['pg/numeric@1']['output'];
      readonly presentacion: CodecTypes['pg/text@1']['output'] | null;
      readonly proveedorId: CodecTypes['pg/int4@1']['output'];
      readonly stockActual: CodecTypes['pg/numeric@1']['output'];
      readonly stockMinimo: CodecTypes['pg/numeric@1']['output'];
      readonly unidadStock: 'UNIDAD' | 'KILOGRAMO';
    };
    readonly productoCategoria: {
      readonly categoriaId: CodecTypes['pg/int4@1']['output'];
      readonly productoId: CodecTypes['pg/int4@1']['output'];
    };
    readonly proveedor: {
      readonly activo: CodecTypes['pg/bool@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nombre: CodecTypes['pg/text@1']['output'];
      readonly telefono: CodecTypes['pg/text@1']['output'] | null;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly categoria: {
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
    };
    readonly listaReposicion: {
      readonly cantidadAReponer: CodecTypes['pg/numeric@1']['input'] | null;
      readonly fechaCreacion: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly productoId: CodecTypes['pg/int4@1']['input'];
      readonly proveedorId: CodecTypes['pg/int4@1']['input'];
    };
    readonly marca: {
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
    };
    readonly movimientoStock: {
      readonly cantidad: CodecTypes['pg/numeric@1']['input'];
      readonly costoCompra: CodecTypes['pg/numeric@1']['input'] | null;
      readonly fecha: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly observacion: CodecTypes['pg/text@1']['input'] | null;
      readonly productoId: CodecTypes['pg/int4@1']['input'];
      readonly proveedorId: CodecTypes['pg/int4@1']['input'] | null;
      readonly tipo: 'ENTRADA' | 'SALIDA';
    };
    readonly producto: {
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly codigoBarra: CodecTypes['pg/text@1']['input'] | null;
      readonly costoCompra: CodecTypes['pg/numeric@1']['input'];
      readonly descripcion: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly marcaId: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly precioEfectivo: CodecTypes['pg/numeric@1']['input'];
      readonly precioSugerido: CodecTypes['pg/numeric@1']['input'] | null;
      readonly precioTarjeta: CodecTypes['pg/numeric@1']['input'];
      readonly presentacion: CodecTypes['pg/text@1']['input'] | null;
      readonly proveedorId: CodecTypes['pg/int4@1']['input'];
      readonly stockActual: CodecTypes['pg/numeric@1']['input'];
      readonly stockMinimo: CodecTypes['pg/numeric@1']['input'];
      readonly unidadStock: 'UNIDAD' | 'KILOGRAMO';
    };
    readonly productoCategoria: {
      readonly categoriaId: CodecTypes['pg/int4@1']['input'];
      readonly productoId: CodecTypes['pg/int4@1']['input'];
    };
    readonly proveedor: {
      readonly activo: CodecTypes['pg/bool@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nombre: CodecTypes['pg/text@1']['input'];
      readonly telefono: CodecTypes['pg/text@1']['input'] | null;
    };
  };
};

export namespace Models {
  export type public_Proveedor = {
    id: CodecTypes['pg/int4@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    telefono: CodecTypes['pg/text@1']['output'] | null;
    email: CodecTypes['pg/text@1']['output'] | null;
    activo: CodecTypes['pg/bool@1']['output'];
    movimientos: public_MovimientoStock[];
    productos: public_Producto[];
    reposiciones: public_ListaReposicion[];
    readonly [RelationKeys]?: 'movimientos' | 'productos' | 'reposiciones';
  };
  export type public_Marca = {
    id: CodecTypes['pg/int4@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    activo: CodecTypes['pg/bool@1']['output'];
    productos: public_Producto[];
    readonly [RelationKeys]?: 'productos';
  };
  export type public_Categoria = {
    id: CodecTypes['pg/int4@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    activo: CodecTypes['pg/bool@1']['output'];
    productos: public_ProductoCategoria[];
    readonly [RelationKeys]?: 'productos';
  };
  export type public_Producto = {
    id: CodecTypes['pg/int4@1']['output'];
    nombre: CodecTypes['pg/text@1']['output'];
    descripcion: CodecTypes['pg/text@1']['output'] | null;
    codigoBarra: CodecTypes['pg/text@1']['output'] | null;
    presentacion: CodecTypes['pg/text@1']['output'] | null;
    unidadStock: 'UNIDAD' | 'KILOGRAMO';
    stockActual: CodecTypes['pg/numeric@1']['output'];
    stockMinimo: CodecTypes['pg/numeric@1']['output'];
    costoCompra: CodecTypes['pg/numeric@1']['output'];
    precioSugerido: CodecTypes['pg/numeric@1']['output'] | null;
    precioEfectivo: CodecTypes['pg/numeric@1']['output'];
    precioTarjeta: CodecTypes['pg/numeric@1']['output'];
    activo: CodecTypes['pg/bool@1']['output'];
    proveedorId: CodecTypes['pg/int4@1']['output'];
    marcaId: CodecTypes['pg/int4@1']['output'];
    categorias: public_ProductoCategoria[];
    marca: public_Marca;
    movimientos: public_MovimientoStock[];
    proveedor: public_Proveedor;
    reposiciones: public_ListaReposicion[];
    readonly [RelationKeys]?: 'categorias' | 'marca' | 'movimientos' | 'proveedor' | 'reposiciones';
  };
  export type public_ProductoCategoria = {
    productoId: CodecTypes['pg/int4@1']['output'];
    categoriaId: CodecTypes['pg/int4@1']['output'];
    categoria: public_Categoria;
    producto: public_Producto;
    readonly [RelationKeys]?: 'categoria' | 'producto';
  };
  export type public_MovimientoStock = {
    id: CodecTypes['pg/int4@1']['output'];
    tipo: 'ENTRADA' | 'SALIDA';
    cantidad: CodecTypes['pg/numeric@1']['output'];
    fecha: CodecTypes['pg/timestamptz-temporal@1']['output'];
    costoCompra: CodecTypes['pg/numeric@1']['output'] | null;
    observacion: CodecTypes['pg/text@1']['output'] | null;
    productoId: CodecTypes['pg/int4@1']['output'];
    proveedorId: CodecTypes['pg/int4@1']['output'] | null;
    producto: public_Producto;
    proveedor: public_Proveedor | null;
    readonly [RelationKeys]?: 'producto' | 'proveedor';
  };
  export type public_ListaReposicion = {
    id: CodecTypes['pg/int4@1']['output'];
    cantidadAReponer: CodecTypes['pg/numeric@1']['output'] | null;
    fechaCreacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
    productoId: CodecTypes['pg/int4@1']['output'];
    proveedorId: CodecTypes['pg/int4@1']['output'];
    producto: public_Producto;
    proveedor: public_Proveedor;
    readonly [RelationKeys]?: 'producto' | 'proveedor';
  };
}

export declare const models: {
  public: {
    Proveedor: Models.public_Proveedor;
    Marca: Models.public_Marca;
    Categoria: Models.public_Categoria;
    Producto: Models.public_Producto;
    ProductoCategoria: Models.public_ProductoCategoria;
    MovimientoStock: Models.public_MovimientoStock;
    ListaReposicion: Models.public_ListaReposicion;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly categoria: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly activo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nombre'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly listaReposicion: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly cantidadAReponer: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly fechaCreacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly productoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly proveedorId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'listaReposicion_productoId_idx_cc0c10f0';
                  readonly prefix: 'listaReposicion_productoId_idx';
                  readonly columns: readonly ['productoId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'listaReposicion_proveedorId_idx_9d4cb4ca';
                  readonly prefix: 'listaReposicion_proveedorId_idx';
                  readonly columns: readonly ['proveedorId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'listaReposicion';
                    readonly columns: readonly ['productoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'producto';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'listaReposicion';
                    readonly columns: readonly ['proveedorId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'proveedor';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly marca: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly activo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nombre'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly movimientoStock: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly tipo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly cantidad: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly fecha: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly costoCompra: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly observacion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly productoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly proveedorId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'movimientoStock_productoId_idx_cc0c10f0';
                  readonly prefix: 'movimientoStock_productoId_idx';
                  readonly columns: readonly ['productoId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'movimientoStock_proveedorId_idx_9d4cb4ca';
                  readonly prefix: 'movimientoStock_proveedorId_idx';
                  readonly columns: readonly ['proveedorId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'movimientoStock';
                    readonly columns: readonly ['productoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'producto';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'movimientoStock';
                    readonly columns: readonly ['proveedorId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'proveedor';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly producto: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descripcion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly codigoBarra: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly presentacion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly unidadStock: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly stockActual: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly stockMinimo: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly costoCompra: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly precioSugerido: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly precioEfectivo: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly precioTarjeta: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly activo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly proveedorId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly marcaId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['codigoBarra'] }];
              indexes: readonly [
                {
                  readonly name: 'producto_proveedorId_idx_9d4cb4ca';
                  readonly prefix: 'producto_proveedorId_idx';
                  readonly columns: readonly ['proveedorId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'producto_marcaId_idx_c1f0cdd9';
                  readonly prefix: 'producto_marcaId_idx';
                  readonly columns: readonly ['marcaId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'producto';
                    readonly columns: readonly ['proveedorId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'proveedor';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'producto';
                    readonly columns: readonly ['marcaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'marca';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly productoCategoria: {
              columns: {
                readonly productoId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly categoriaId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['productoId', 'categoriaId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'productoCategoria_productoId_idx_cc0c10f0';
                  readonly prefix: 'productoCategoria_productoId_idx';
                  readonly columns: readonly ['productoId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'productoCategoria_categoriaId_idx_63b46427';
                  readonly prefix: 'productoCategoria_categoriaId_idx';
                  readonly columns: readonly ['categoriaId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'productoCategoria';
                    readonly columns: readonly ['productoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'producto';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'productoCategoria';
                    readonly columns: readonly ['categoriaId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'categoria';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly proveedor: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly telefono: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly activo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly TipoMovimiento: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ENTRADA', 'SALIDA'];
            };
            readonly UnidadStock: {
              readonly kind: 'valueSet';
              readonly values: readonly ['UNIDAD', 'KILOGRAMO'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly proveedor: { readonly namespace: 'public' & NamespaceId; readonly model: 'Proveedor' };
    readonly marca: { readonly namespace: 'public' & NamespaceId; readonly model: 'Marca' };
    readonly categoria: { readonly namespace: 'public' & NamespaceId; readonly model: 'Categoria' };
    readonly producto: { readonly namespace: 'public' & NamespaceId; readonly model: 'Producto' };
    readonly productoCategoria: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ProductoCategoria';
    };
    readonly movimientoStock: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'MovimientoStock';
    };
    readonly listaReposicion: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ListaReposicion';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Categoria: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly activo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly productos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ProductoCategoria';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['categoriaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'categoria';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly activo: { readonly column: 'activo' };
              };
            };
          };
          readonly ListaReposicion: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly cantidadAReponer: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly fechaCreacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly productoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly proveedorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly producto: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Producto';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['productoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly proveedor: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Proveedor';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['proveedorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'listaReposicion';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly cantidadAReponer: { readonly column: 'cantidadAReponer' };
                readonly fechaCreacion: { readonly column: 'fechaCreacion' };
                readonly productoId: { readonly column: 'productoId' };
                readonly proveedorId: { readonly column: 'proveedorId' };
              };
            };
          };
          readonly Marca: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly activo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly productos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Producto';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['marcaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'marca';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly activo: { readonly column: 'activo' };
              };
            };
          };
          readonly MovimientoStock: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tipo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly cantidad: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly fecha: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly costoCompra: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly observacion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly productoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly proveedorId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly producto: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Producto';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['productoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly proveedor: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Proveedor';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['proveedorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'movimientoStock';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly tipo: { readonly column: 'tipo' };
                readonly cantidad: { readonly column: 'cantidad' };
                readonly fecha: { readonly column: 'fecha' };
                readonly costoCompra: { readonly column: 'costoCompra' };
                readonly observacion: { readonly column: 'observacion' };
                readonly productoId: { readonly column: 'productoId' };
                readonly proveedorId: { readonly column: 'proveedorId' };
              };
            };
          };
          readonly Producto: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descripcion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly codigoBarra: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly presentacion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly unidadStock: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly stockActual: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly stockMinimo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly costoCompra: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly precioSugerido: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly precioEfectivo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly precioTarjeta: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly activo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly proveedorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly marcaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly categorias: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ProductoCategoria';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['productoId'];
                };
              };
              readonly marca: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Marca';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['marcaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly movimientos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'MovimientoStock';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['productoId'];
                };
              };
              readonly proveedor: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Proveedor';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['proveedorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly reposiciones: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ListaReposicion';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['productoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'producto';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly descripcion: { readonly column: 'descripcion' };
                readonly codigoBarra: { readonly column: 'codigoBarra' };
                readonly presentacion: { readonly column: 'presentacion' };
                readonly unidadStock: { readonly column: 'unidadStock' };
                readonly stockActual: { readonly column: 'stockActual' };
                readonly stockMinimo: { readonly column: 'stockMinimo' };
                readonly costoCompra: { readonly column: 'costoCompra' };
                readonly precioSugerido: { readonly column: 'precioSugerido' };
                readonly precioEfectivo: { readonly column: 'precioEfectivo' };
                readonly precioTarjeta: { readonly column: 'precioTarjeta' };
                readonly activo: { readonly column: 'activo' };
                readonly proveedorId: { readonly column: 'proveedorId' };
                readonly marcaId: { readonly column: 'marcaId' };
              };
            };
          };
          readonly ProductoCategoria: {
            readonly fields: {
              readonly productoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly categoriaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly categoria: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Categoria';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['categoriaId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly producto: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Producto';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['productoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'productoCategoria';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly productoId: { readonly column: 'productoId' };
                readonly categoriaId: { readonly column: 'categoriaId' };
              };
            };
          };
          readonly Proveedor: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly telefono: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly activo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly movimientos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'MovimientoStock';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['proveedorId'];
                };
              };
              readonly productos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Producto';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['proveedorId'];
                };
              };
              readonly reposiciones: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ListaReposicion';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['proveedorId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'proveedor';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nombre: { readonly column: 'nombre' };
                readonly telefono: { readonly column: 'telefono' };
                readonly email: { readonly column: 'email' };
                readonly activo: { readonly column: 'activo' };
              };
            };
          };
        };
        readonly enum: {
          readonly UnidadStock: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'UNIDAD'; readonly value: 'UNIDAD' },
              { readonly name: 'KILOGRAMO'; readonly value: 'KILOGRAMO' },
            ];
          };
          readonly TipoMovimiento: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ENTRADA'; readonly value: 'ENTRADA' },
              { readonly name: 'SALIDA'; readonly value: 'SALIDA' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
